site_name: Low level module documentation
nav:
    - Getting started: 'index.md'
    - Sensors: 'sensors.md'
    - Motors: 'motors.md'
    - Sound: 'sound.md'
    - Led: 'led.md'
    - Image: 'image_test.md'
    - Motion: 'motion.md'
    - Display: 'display.md'
    - Button: 'button.md'
    - Data types and constants: 'data_types.md'
    - Virtual Com Port: 'VCP.md'
    - Battery: 'battery.md'
    - Bluetooth: 'bluetooth.md'
    - Config: 'config.md'
    - File transfer: 'file_transfer.md'
    - Info : 'info.md'
    - Port : 'port.md'
    - power_off: 'power_off.md'
    - powerdown_timeout: 'powerdown.md'
    - repl_restart: 'repl_restart.md'
    - reset: 'reset.md'
    - status: 'status.md'
    - supervision: 'supervision.md'
    - temperature: 'temperature.md'
    - hub: 'hub.md'
theme: readthedocs
extra_css: ['custom.css']
