site_name: Low level module documentation
nav:
    - Getting started: 'index.md'
    - Hub: 'hub.md'
    - Led: 'led.md'
    - Sensors: 'sensors.md'
    - Motors: 'motors.md'
    - Sound: 'sound.md'
    - Image: 'image_test.md'
    - Motion: 'motion.md'
    - Display: 'display.md'
    - Button: 'button.md'
    - Data types and constants: 'data_types.md'
    - Virtual Com Port: 'VCP.md'
    - Battery: 'battery.md'
    - Bluetooth: 'bluetooth.md'
    - Config: 'config.md'
    - Port : 'port.md'
    - supervision: 'supervision.md'

theme: readthedocs
extra_css: ['custom.css']
