site_name: Marshmallow Generator
nav:
    - 'index.md'
    - 'sensors.md'
    - 'motors.md'
    - 'sound.md'
    - 'led.md'
    - 'image.md'
    - 'motion.md'
    - 'button.md'
    - 'test_link.md'
theme: readthedocs
