site_name: Low level module documentation
nav:
    - Getting started: 'index.md'
    - Sensors: 'sensors.md'
    - Motors: 'motors.md'
    - Sound: 'sound.md'
    - Led: 'led.md'
    - Image: 'image_test.md'
    - Motion: 'motion.md'
    - Display: 'display.md'
    - Button: 'button.md'
    - Data types: 'data_types.md'
theme: readthedocs
extra_css: ['custom.css']
