site_name: Marshmallow Generator
nav:
    - 'index.md'
    - 'sensors.md'
    - 'motors.md'
    - 'sound.md'
    - 'led.md'
    - 'image_test.md'
    - 'motion.md'
    - 'display.md'
    - 'button.md'
    - 'data_types.md'
    - 'test_link.md'
theme: readthedocs
extra_css: [custom.css]
