site_name: Unofficial hub module documentation
nav:
    - Getting started: 'index.md'
    - Hub: 'hub.md'
    - Led: 'led.md'
    - Sound: 'sound.md'
    - Image: 'image.md'
    - Display: 'display.md'
    - Button: 'button.md'
    - Motion: 'motion.md'
    - Port : 'port.md'
    - Sensors (Device): 'sensors.md'
    - Motor: 'motors.md'  
    - Virtual Com Port: 'VCP.md'  
    - Battery: 'battery.md'
    - Data types and constants: 'data_types.md'

#   - Bluetooth: 'bluetooth.md'
#   - Config: 'config.md'
#   - supervision: 'supervision.md'
theme: readthedocs
extra_css: ['custom.css']
copyright: © Copyright 2021 Nard Strijbosch
site_author: Nard Strijbosch
extra:
    date: 18th of Januari
markdown_extensions:
- toc:
    permalink: True
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto: n.strijbosch@gmail.com